kind: MLApp
metadata:
  name: openvino-facenet
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: align-images
    resources:
    - command: python align_dataset_mtcnn.py
        $FACES_DIR $TRAINING_DIR/aligned-images
        {{- if .bg_remove.value }}
        --bg-remove-path $BG_REMOVE_DIR
        {{- end }}
        --image_size 160
        --margin 32
      default_volume_mapping: true
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino-gpu
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: train-classifier
    resources:
    - command: python classifier_train.py
        TRAIN $TRAINING_DIR/aligned-images
        --model $FACENET_DIR/facenet.xml
        {{- if .bg_remove.value }}
        --bg-remove-path $BG_REMOVE_DIR
        {{- end }}
        --classifier $TRAINING_DIR/classifier.pkl
        --algorithm kNN --flip --noise --noise-count 3
        --driver openvino
        --device CPU
      default_volume_mapping: true
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: validate-classifier
    resources:
    - command: python classifier_train.py
        CLASSIFY $TRAINING_DIR/aligned-images
        --model $FACENET_DIR/facenet.xml
        --classifier $TRAINING_DIR/classifier.pkl
        --upload-model
        --upload-threshold 0.9
        --driver openvino
        --device CPU
      default_volume_mapping: true
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pipeline
    resources:
    - command: python pipeline.py 0.9 openvino
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.9.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.9.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: model-converter
    resources:
    - command: python openvino_converter.py
        --all
        --training_dir $TRAINING_DIR/model
        --push_model true
        --facenet_graph $FACENET_DIR/20180408-102900.pb
        --target CPU
        --align_model_dir $FACENET_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/openvino:cpu-36
        gpu: ""
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  uix:
  - default_volume_mapping: true
    displayName: Jupyter
    images:
      cpu: kuberlab/tensorflow:cpu-36-1.9.0-full
    name: jupyter
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 64Mi
  serving:
  - name: serving
    displayName: OpenVino Serving
    images:
      cpu: "kuberlab/serving:latest-openvino"
      gpu: "kuberlab/serving:latest-openvino-gpu"
    command: >-
      kuberlab-serving --driver openvino --model-path $FACENET_DIR/facenet.xml --hooks serving_hook.py
      {{- if .bg_remove.value }}
      -o bg-remove-path $BG_REMOVE_DIR
      {{- end }}
      -o classifier=$MODEL_DIR/classifier.pkl -o flexible_batch_size=True
      -o use_face_detection=true -o face_detection_path=$FACE_DETECTION_DIR/face-detection.xml
      -o device=CPU
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 200m
        memory: 256M
      limits:
        cpu: 4000m
        memory: 4Gi
    spec:
      params:
      - name: input
        type: bytes
      response:
      - name: output
        type: bytes
        shape:
        - 1
        - -1
      - name: table_output
        type: string
        shape:
        - -1
      rawInput: true
      model: any
      template: "image"
      outFilter:
        - output
      outMimeType: "image/jpeg"
    workDir: $SRC_DIR
    sources:
    - gitRepo:
        repository: {{ gitRepo .src.value }}
        accountId: '{{ .src.accountId }}'
        revision: '{{ .src.revision }}'
      name: src
      subPath: {{ gitSubPath .src.value }}/src
    - name: facenet
      model:
        workspace: {{ .model.workspace }}
        model: {{ .model.value }}
        version: {{ .model.version }}
    - name: face-detection
      model:
        workspace: kuberlab-demo
        model: openvino-face-detection
        version: 1.4.0-cpu
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  volumes:
  - clusterStorage: '{{ .storage.value }}'
    name: training
  - gitRepo:
      repository: {{ gitRepo .src.value }}
      accountId: '{{ .src.accountId }}'
      revision: '{{ .src.revision }}'
    isLibDir: false
    name: src
    subPath: {{ gitSubPath .src.value }}/src
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: true
    name: lib
  - clusterStorage: '{{ .storage.value }}'
    mountPath: /notebooks
    name: code
    subPath: code
  - isLibDir: false
    name: facenet
    model:
      workspace: {{ .model.workspace }}
      model: {{ .model.value }}
      version: {{ .model.version }}
  - isLibDir: false
    name: faces
    {{- if .faces.value }}
    datasetFS:
      workspace: {{ .faces.workspace }}
      dataset: {{ .faces.value }}
      version: {{ .faces.version }}
    {{- else }}
    clusterStorage: {{ .storage.value }}
    {{- end }}
    {{- if .bg_remove.value }}
  - isLibDir: false
    name: bg_remove
    model:
      workspace: {{ .bg_remove.workspace }}
      model: {{ .bg_remove.value }}
      version: {{ .bg_remove.version }}
    {{- end }}
