kind: MLApp
metadata:
  name: openvino-facenet
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: align-images
    resources:
    - command: python align_dataset_mtcnn.py
        $FACES_DIR /tmp/faces --image_size 160  --margin 32 --model_dir $FACENET_DIR --push {{ .faces.value }}
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: train-classifier
    resources:
    - command: python3 classifier_train.py TRAIN $FACES_DIR --model $FACENET_DIR/facenet.xml --classifier $TRAINING_DIR/classifier.pkl --driver openvino --device CPU
      default_volume_mapping: true
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: validate-classifier
    resources:
    - command: python3 classifier_train.py CLASSIFY $FACES_DIR --model $FACENET_DIR/facenet.xml --classifier $TRAINING_DIR/classifier.pkl --upload-model --upload-threshold 0.9 --driver openvino --device CPU
      default_volume_mapping: true
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: pipeline
    resources:
    - command: python pipeline.py 0.9 openvino
      default_volume_mapping: true
      images:
        cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
        gpu: kuberlab/tensorflow:gpu-36-1.7.0-full
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  - name: model-converter
    resources:
    - command: python openvino_converter.py --all --training_dir $TRAINING_DIR/model --push_model true --facenet_graph $FACENET_DIR/20180408-102900.pb --target CPU --align_model_dir $FACENET_DIR
      default_volume_mapping: true
      images:
        cpu: kuberlab/openvino:cpu-36
        gpu: ""
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 64Mi
      restartPolicy: Never
      workDir: $SRC_DIR
  uix:
  - default_volume_mapping: true
    displayName: Jupyter
    images:
      cpu: kuberlab/tensorflow:cpu-36-1.7.0-full
    name: jupyter
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 64Mi

  serving:
  - name: serving
    displayName: OpenVino Serving
    images:
      cpu: "kuberlab/serving:latest-openvino"
    command: "kuberlab-serving --driver openvino --model-path $FACENET_DIR/facenet.xml --hooks serving_hook.py -o classifier=$TRAINING_DIR/classifier.pkl -o flexible_batch_size=True -o resolutions=14x19,19x27,26x37,37x52,52x74,73x104,103x146,145x206,205x290 -o use_tf=true -o tf_path=$FACENET_DIR"
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 100m
        memory: 125Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    spec:
      params:
      - name: input
        type: bytes
      rawInput: true
      model: any
      outFilter:
        - output
      outMimeType: "image/png"
    workDir: $SRC_DIR
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
    volumes:
    - name: training
    - name: src
    - name: facenet
  volumes:
  - clusterStorage: '{{ .storage.value }}'
    name: training
  - gitRepo:
      repository: {{ gitRepo .src.value }}
      accountId: '{{ .src.accountId }}'
      revision: '{{ .src.revision }}'
    isLibDir: false
    name: src
    subPath: {{ gitSubPath .src.value }}/src
  - clusterStorage: '{{ .storage.value }}'
    isLibDir: true
    name: lib
  - clusterStorage: '{{ .storage.value }}'
    mountPath: /notebooks
    name: code
    subPath: code
  - isLibDir: false
    name: facenet
    model:
      workspace: {{ .model.workspace }}
      model: {{ .model.value }}
      version: {{ .model.version }}
  - isLibDir: false
    name: faces
    {{- if .faces.value }}
    datasetFS:
      workspace: {{ .faces.workspace }}
      dataset: {{ .faces.value }}
      version: {{ .faces.version }}
    {{- else }}
    clusterStorage: {{ .storage.value }}
    {{- end }}
